server:
  port: 9090
spring:
  application:
    name: register #指定服务名
eureka:
  instance:
#    prefer-ip-address: true
    hostname: localhost
    #    localhost
    appname: 注册服务-中心
  client:
    registerWithEureka: false  # 单点的时候设置为 false 禁止注册自身
    fetchRegistry: false
  serviceUrl:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  #    defaultZone: http://localhost:${server.port}/eureka/
  #    eureka.client.serviceUrl.defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 4000
security:
  basic:
    enabled: false








