spring:
  application:
    name: crud-demo  ## 应用程序名称，后面会在消费者中用到
eureka:
  instance:
    preferIpAddress: true
    appname: boot-CRUD-demo
  client:
    instance:
      prefer-ip-address: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9090/eureka/   ## 注册到 eureka

#  localhost
security:
  basic:
    enabled: false

